Solution
mate-academy/py-shop-trip pull request #258
Opened 2023-04-23 10:03 UTC by Dmytry95

![image](https://user-images.githubusercontent.com/126564500/233833211-e3685bf7-76b6-4297-97cc-5590a4b59f18.png)
what is that?

2023-04-23 11:42 UTC, vasylhnatiuk requested changes
you didn't do it  `When the customer arrives at the shop his location should equal to shop location... After the shop he arrives home `

2023-04-24 09:04 UTC, ArsenPidhoretskyi requested changes

2023-04-24 09:04 UTC, ArsenPidhoretskyi commented on app/customer.py
> +            shops_list: list[Shop],
```suggestion
            shops: list[Shop],

```
Why you need suffix?

2023-04-24 09:04 UTC, ArsenPidhoretskyi commented on app/customer.py
> +            ] = shop
In this case use dict-comprenhension

2023-04-24 09:04 UTC, ArsenPidhoretskyi commented on app/customer.py
> +            / 100
```suggestion
        trip_fuel_consumption = (
            total_distance * self.car["fuel_consumption"]
            / 100
        )

```

2023-04-24 09:04 UTC, ArsenPidhoretskyi commented on app/customer.py
> +            product_expenses += amount_to_buy * shop.products[product]
Use sum function

2023-04-24 09:04 UTC, ArsenPidhoretskyi commented on app/shop.py
> +                f"{self.products[product] * amount} dollars")
```suggestion
            plural = "s" if amount > 1 else ""
            print(f"{amount} {product}{plural} for {self.products[product] * amount} dollars")
```

2023-04-24 10:09 UTC, ArsenPidhoretskyi requested changes
All Remarks is not fixed

2023-04-24 10:32 UTC, ArsenPidhoretskyi approved these changes
Well done!

2024-05-21 19:19 UTC, closed without merging