py-shop-trip-v0
mate-academy/py-shop-trip pull request #297
Opened 2023-06-06 11:37 UTC by muriakula

I have a problem with pytest. pytest cannot find the config.json file

2023-06-06 14:38 UTC, olena-hul requested changes

2023-06-06 14:38 UTC, olena-hul commented on app/car.py
> +        return cls(car["brand"], car["fuel_consumption"])
rename method to `create`

2023-06-06 14:38 UTC, olena-hul commented on app/customer.py
> +    def set_customer_from_file(cls, customers: dict) -> list:
Use better method name

2023-06-06 14:38 UTC, olena-hul commented on app/shop.py
> +    def set_shop_from_file(cls, shops: dict) -> list:
Use better method name

2023-06-06 14:38 UTC, olena-hul commented on app/json_data.py
> +    ttl_product_price = 0
Use full names, ttl is commonly used to specify `time to live`, not total

2023-06-07 08:55 UTC, Bohdan-Salamakha requested changes

2023-06-07 08:55 UTC, Bohdan-Salamakha commented on app/customer.py
> +    def create_customers(cls, customers: dict) -> list:
add additional typehint for list inner objects like list[YOUR_VALUE_TYPE]
for example: list that contains string elements has typehint list[str]

2023-06-07 08:55 UTC, Bohdan-Salamakha commented on app/shop.py
> +    def create_shops(cls, shops: dict) -> list:
add additional typehint for list inner objects like list[YOUR_VALUE_TYPE]
for example: list that contains string elements has typehint list[str]

2023-06-07 08:55 UTC, Bohdan-Salamakha commented on app/main.py
> +                  )
```suggestion
            print(
                  f"{customer.name} rides to {the_best_shop.name}\n"
                  f"\nDate: "
                  f"{datetime.datetime.now().strftime('%d/%m/%Y %H:%M:%S')}\n"
                  f"Thanks, {customer.name}, for your purchase!\n"
                  f"{the_best_shop.receipt}\nSee you again!\n"
                  f"\n{customer.name} rides home\n"
                  f"{customer.name} now has "
                  f"{customer.money - min_shop_cost} dollars\n"
                  )
```

2023-06-07 08:55 UTC, Bohdan-Salamakha commented on app/json_data.py
> +def distance(point1: list, point2: list) -> float:
add additional typehint for list inner objects like list[YOUR_VALUE_TYPE]
for example: list that contains string elements has typehint list[str]

2023-06-07 16:54 UTC, Bohdan-Salamakha approved these changes

2024-10-29 09:58 UTC, closed without merging