Solution v1.0.0
mate-academy/py-shop-trip pull request #298
Opened 2023-06-06 20:10 UTC by gleblitvinenko

2023-06-07 07:11 UTC, Grayder0152 requested changes

2023-06-07 07:11 UTC, Grayder0152 commented on app/main.py
> +            print("Date: 04/01/2021 12:33:41")
Why hardcode?

2023-06-07 07:12 UTC, gleblitvinenko commented on app/main.py
> +            print("Date: 04/01/2021 12:33:41")
Pytest didn't pass tests without it

2023-06-08 10:22 UTC, ArsenPidhoretskyi requested changes
Good job!

2023-06-08 10:22 UTC, ArsenPidhoretskyi commented on app/main.py
> +                customer.product_cart.get(key) * shop.products.get(key)
FYI info get can return None

2023-06-08 10:22 UTC, ArsenPidhoretskyi commented on app/utils.py
> +            for shop in data_from_file["shops"]]
```suggestion
        shops = [
            Shop(
                shop.get("name"),
                shop.get("location"),
                shop.get("products")
            )
            for shop in data_from_file["shops"]
        ]

```

2023-06-08 10:22 UTC, ArsenPidhoretskyi commented on app/utils.py
> +            for shop in data_from_file["shops"]]
Unreadable code....

2023-06-14 11:40 UTC, vasylhnatiuk approved these changes

2026-03-10 17:47 UTC, closed without merging