[Errno 2] No such file or directory: 'config.json'
mate-academy/py-shop-trip pull request #333
Opened 2023-07-16 01:16 UTC by sbilikepy

Can't import json to pass tests

2023-07-16 11:51 UTC, vasylhnatiuk requested changes
![image](https://github.com/mate-academy/py-shop-trip/assets/104974881/25bc2a9a-9721-40f4-820b-632a4fb605f2)
fix test

2023-07-17 00:48 UTC, sbilikepy commented
It looks like my output matches the result of the test (apart from the mock time), perhaps except for the "\n" spacings. Why is it important?

2023-07-17 07:43 UTC, Grayder0152 requested changes

2023-07-17 07:43 UTC, Grayder0152 commented on app/main.py
> +        customers[f"{customer['name']}"] = Customer(
```suggestion
        customers[customer['name']] = Customer(
```

2023-07-17 07:43 UTC, Grayder0152 commented on app/main.py
> +        shops[f"{shop['name']}"] = Shop(
```suggestion
        shops[shop['name']] = Shop(
```

2023-07-17 18:41 UTC, vsmutok requested changes
fix tests

2023-07-18 17:40 UTC, ArsenPidhoretskyi requested changes

2023-07-18 17:40 UTC, ArsenPidhoretskyi commented on app/customer.py
> +        return f"{self.name}"
f string is redundant
```suggestion
        return self.name
```

2023-07-18 17:40 UTC, ArsenPidhoretskyi commented on app/cost_calculation.py
> +                    self.results[customer] = {shop: trip_total_cost}
just save these values inside variables no need to save them inside dict

2023-07-19 08:13 UTC, ArsenPidhoretskyi requested changes

2023-07-19 08:13 UTC, ArsenPidhoretskyi commented on app/cost_calculation.py
> +            Shop.sale_of_goods(best_shop, customer)
Call method to instance no need to write Class.method(instance) you can do instance.method()

2023-07-19 08:13 UTC, ArsenPidhoretskyi commented on app/shop.py
> +        return f"{self.name}"
f-string is redundant

2023-07-19 08:13 UTC, ArsenPidhoretskyi commented on app/shop.py
> +                    total_cost += (amount * price)
```suggestion
        for product, amount in customer.product_cart.items():
                total_cost += (amount * self.products[product])
```
Nested loop is redundant

2023-07-19 11:26 UTC, vasylhnatiuk approved these changes

2026-07-30 15:20 UTC, closed without merging