'Solution'
mate-academy/py-shop-trip pull request #41
Opened 2022-06-27 13:46 UTC by LaskoA

Please check it, thank you :)

2022-06-27 13:50 UTC, Abnormaltype commented on app/main.py
> +        print(f"{customers[person]['name']}'s trip to the Shop \'24/7\' "
```suggestion
        print(f"{customers[person]['name']}'s trip to the Shop \'24/7\' "
```

create variable for {customers[person]['name'] and don't use \ in  \'24/7\'

2022-06-27 13:51 UTC, Abnormaltype commented on app/main.py
> +        food = customers[person]['product_cart']
use `""` instead od `''`

2022-06-27 13:51 UTC, Abnormaltype commented on app/main.py
> +                print(f"{customers[person]['name']} rides to Shop \'24/7\'")
the same here

2022-06-27 13:53 UTC, Abnormaltype commented on app/main.py
> +            print("Date: 11/03/2020 13:15:34")
it's not correct

2022-06-27 13:53 UTC, Abnormaltype commented on app/main.py
> +            print("")
it's not correct, use` \n` in previous `print()`

2022-06-27 13:53 UTC, Abnormaltype commented on app/main.py
> +            print("")
the same here

2022-06-27 13:54 UTC, Abnormaltype commented on app/main.py
> +            print("")
the same here

2022-06-27 13:54 UTC, Abnormaltype commented on app/main.py
> +                  f"{food['butter']} butters for {butter_price} dollars")
make loop please, DRY

2022-06-27 13:54 UTC, Abnormaltype commented on app/main.py
> +                shops[shop_id]["products"]["butter"]
make loop, DRY

2022-06-29 11:41 UTC, LaskoA commented
Please check now, thank you)

2022-06-29 11:44 UTC, Abnormaltype requested changes

2022-06-29 11:44 UTC, Abnormaltype commented on app/main.py
> +        food = customers[person]['product_cart']
the same problem

2022-06-29 11:44 UTC, Abnormaltype commented on app/main.py
> +        name = customers[person]['name']
the same

2022-06-29 12:02 UTC, LaskoA commented
attempt #3....

2022-06-29 12:13 UTC, Abnormaltype requested changes
fix my suggestions

2022-06-29 12:21 UTC, LaskoA commented
done)

2022-06-29 12:22 UTC, Abnormaltype approved these changes
good job!

2022-06-29 12:58 UTC, closed without merging